#!/bin/sh

LOCKFILE=/tmp/display_lockfile
GNUSER=`ps aux | grep gnome-session | grep -v grep | head -n1 | cut -f1 -d' '`

if [ -z "$GNUSER" ]; then
  echo no gnome-session found >&2
  exit 1
fi
echo Detected $GNUSER running gnome-session

if [ -f $LOCKFILE ]; then
  echo error: lockfile still exists >&2
  exit 1
fi

VGA=`sudo -u $GNUSER DISPLAY=:0 xrandr | grep 'VGA1 connected' | wc -l`
echo vga $VGA

touch $LOCKFILE
sleep 10
rm $LOCKFILE